### ISSUE TITLE
Relax required version of System.Collections.Immutable

### ISSUE THREAD

**Issue by CoenraadS** [StephenCleary/Disposables#16]
Hello

I noticed this project has a dependency of `<PackageReference Include="System.Collections.Immutable" Version="1.7.1" />`

I'm currently stuck a bit in nuget resolution hell, and was wondering if it would possible to relax this to be something like [1.0,2.0) (anything between 1 and 2)

**Comment by StephenCleary** [comment]
That's a great idea, and I should probably do the same for other dependencies, too.

On vacation ATM, but I should be able to address this in a couple weeks.

**Comment by StephenCleary** [comment]
I can reduce it down to 1.5, but not any lower due to NuGet's resolution rules.

**Comment by StephenCleary** [comment]
Forgot to close this issue; this was fixed in v2.4.0.
