### ISSUE TITLE
Open Questions for AsyncDisposable

### ISSUE THREAD

**Issue by StephenCleary** [StephenCleary/Disposables#5]
### Naming

Currently we have `AnonymousAsyncDisposable` and `CollectionAsyncDisposable`. Should these be `AsyncAnonymousDisposable` and `AsyncCollectionDisposable`?

### Concurrency Defaults

Both the `Anonymous` and `Collection` disposables may have multiple "children" to invoke/dispose. In the synchronous world, these children are invoked/disposed synchronously, one after another.

Currently the `Async` types will default to concurrent invocation/disposal, essentially starting each "child" and then doing an `await Task.WhenAll`. Is this expected behavior, or should we default to serial?

### Concurrency as an Option

Currently the `Async` types take a flag at creation that allows specifying that the "children" should be invoked/disposed one at a time. Should this be a flag, or should there be a separate type, e.g., adding `SerialAnonymousAsyncDisposable` and `SerialCollectionAsyncDisposable`?

### Thread Pool as an Option

Currently the `Async` types invoke/dispose their children directly. However, the `CollectionAsyncDisposable` type is intended to be able to hold both synchronous *and* asynchronous disposable children [through an extension method that converts any `IDisposable` to an `IAsyncDisposable`](https://github.com/StephenCleary/Disposables/blob/ec6330e1e49e553ec883332cfcd5c83640b28403/src/Nito.Disposables/DisposableExtensions.cs#L18). This means that even with the default `AsyncDisposeFlags.ExecuteConcurrently` flag, any children that are actually synchronous will prevent later children from starting to execute. To avoid this, should we add a new `AsyncDisposeFlags.DisposeOnThreadPool` to queue all child disposal to the thread pool?

**Comment by strongbutgood** [comment]
**Naming**
The current naming (`AnonymousAsyncDisposable`) better aligns with the interface name `IAsyncDisposable`. Disconnecting the async from disposable disconnects the association with the interface name.

**Concurrency**
Asynchrony doesn't necessarily imply concurrency within the current task so a serial implementation would be more expected. As such `ConcurrentAnonymousAsyncDisposable` and `ConcurrentCollectionAsyncDisposable` may be better options. I haven't come across a situation where I've had more than one delegate invoked by the disposable yet, and I haven't used the `IAsyncDisposable` interface either.

**Comment by StephenCleary** [comment]
Thanks for your feedback! I'm publishing 2.1.0 shortly, which will keep the current async naming, and use serial execution rather than concurrent by default.
