### ISSUE TITLE
3.0-era plans

### ISSUE THREAD

**Issue by StephenCleary** [StephenCleary/Disposables#7]
Expected changes:

- ~Change `SingleDisposable.TryUpdateContext` semantics so that if it is called during disposal, it will block on that disposal *before* disposing the new child.~ Done as part of 2.1.0 (considering this a bug fix even though it does change semantics)
- Move `SingleDisposable` / `SingleNonblockingDisposable` into a different namespace so advanced users can "opt in".

Possibly before 3.0-era:
- ~Add `AddRange` for the collection. => Moved to #11~ Not planning to do this.
- ~Add a ref-counted disposable. => Moved to #12~ Done as of 2.3.0.
- ~Consider adding a simple "FixDisposable" that only wraps a single underlying disposable.~ Not planning to do this.

**Comment by RKayCH** [comment]
(y) me likes! 
Thank you very much for all your efforts!

**Comment by StephenCleary** [comment]
Idea:

- ~Define a simple `Disposable` and `AsyncDisposable` for the 95% use case so people don't have to remember `AnonymousDisposable` / `AnonymousAsyncDisposable`.~ Done as of 2.2.0.

**Comment by StephenCleary** [comment]
- Deprecate `AnonymousDisposable` / `AnonymousAsyncDisposable`.
- Change Single usage from inheritance to composition.

**Comment by StephenCleary** [comment]
All changes above are in `v3.0.0-pre01`.

**Comment by StephenCleary** [comment]
These improvements are in 2.1.0-2.3.0, and the backwards-incompatible changes are only usage changes that don't provide new functionality, so I'm closing this for now (and staying on 2.x for the foreseeable future).
